name: Build AsciiDoc to HTML and PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Asciidoctor and Asciidoctor PDF
      run: |
        sudo apt-get update
        sudo apt-get install -y asciidoctor
        sudo gem install asciidoctor-pdf

    - name: Build HTML
      run: asciidoctor -o docs/index.html book/book.adoc

    - name: Build PDF
      run: asciidoctor-pdf -a pdf-style=./theme/theme.yml -o docs/book.pdf book/book.adoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs

    - name: Create Tag
      id: create_tag
      run: |
        TAG_NAME=$(date +%Y%m%d%H%M%S)
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.tag_name }}
        release_name: Release ${{ env.tag_name }}
        draft: false
        prerelease: false

    - name: Set Release Upload URL
      run: echo "RELEASE_UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ env.RELEASE_UPLOAD_URL }}
        asset_path: ./docs/book.pdf
        asset_name: book.pdf
        asset_content_type: application/pdf
